version: '2'

networks:
  app-network:
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1

services:
  app:
    image: sharp-test
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    dns: 208.67.222.222
    networks:
      - app-network
